import type { Metadata } from "next";
import "./globals.css";

import ReduxProvider from "@/stores/redux-provider";
import { CustomToaster } from "@/shared-components/src/components/toaster/toaster";
import ToasterProvider from "./ToasterProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
          <ToasterProvider />
        </ReduxProvider>
      </body>
    </html>
  );
}
